//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.26 at 10:59:03 AM IST 
//


package std.iso20022.xsd.camt_052_001_13;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.camt_052_001_12 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.053.001.13", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.camt_052_001_12
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery1 }
     * 
     */
    public OriginalBusinessQuery1 createOriginalBusinessQuery1() {
        return new OriginalBusinessQuery1();
    }

    /**
     * Create an instance of {@link SequenceRange1Choice }
     * 
     */
    public SequenceRange1Choice createSequenceRange1Choice() {
        return new SequenceRange1Choice();
    }

    /**
     * Create an instance of {@link ChargesRecord8 }
     * 
     */
    public ChargesRecord8 createChargesRecord8() {
        return new ChargesRecord8();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification3 }
     * 
     */
    public GenericOrganisationIdentification3 createGenericOrganisationIdentification3() {
        return new GenericOrganisationIdentification3();
    }

    /**
     * Create an instance of {@link CardEntry5 }
     * 
     */
    public CardEntry5 createCardEntry5() {
        return new CardEntry5();
    }

    /**
     * Create an instance of {@link TaxRecordDetails3 }
     * 
     */
    public TaxRecordDetails3 createTaxRecordDetails3() {
        return new TaxRecordDetails3();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification23 }
     * 
     */
    public FinancialInstitutionIdentification23 createFinancialInstitutionIdentification23() {
        return new FinancialInstitutionIdentification23();
    }

    /**
     * Create an instance of {@link TotalsPerBankTransactionCode5 }
     * 
     */
    public TotalsPerBankTransactionCode5 createTotalsPerBankTransactionCode5() {
        return new TotalsPerBankTransactionCode5();
    }

    /**
     * Create an instance of {@link DocumentLineInformation2 }
     * 
     */
    public DocumentLineInformation2 createDocumentLineInformation2() {
        return new DocumentLineInformation2();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchange4 }
     * 
     */
    public AmountAndCurrencyExchange4 createAmountAndCurrencyExchange4() {
        return new AmountAndCurrencyExchange4();
    }

    /**
     * Create an instance of {@link EntryTransaction15 }
     * 
     */
    public EntryTransaction15 createEntryTransaction15() {
        return new EntryTransaction15();
    }

    /**
     * Create an instance of {@link TaxCharges2 }
     * 
     */
    public TaxCharges2 createTaxCharges2() {
        return new TaxCharges2();
    }

    /**
     * Create an instance of {@link AccountInterest4 }
     * 
     */
    public AccountInterest4 createAccountInterest4() {
        return new AccountInterest4();
    }

    /**
     * Create an instance of {@link PriceRateOrAmount3Choice }
     * 
     */
    public PriceRateOrAmount3Choice createPriceRateOrAmount3Choice() {
        return new PriceRateOrAmount3Choice();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link DocumentType1 }
     * 
     */
    public DocumentType1 createDocumentType1() {
        return new DocumentType1();
    }

    /**
     * Create an instance of {@link GenericIdentification3 }
     * 
     */
    public GenericIdentification3 createGenericIdentification3() {
        return new GenericIdentification3();
    }

    /**
     * Create an instance of {@link GenericIdentification1 }
     * 
     */
    public GenericIdentification1 createGenericIdentification1() {
        return new GenericIdentification1();
    }

    /**
     * Create an instance of {@link CardAggregated2 }
     * 
     */
    public CardAggregated2 createCardAggregated2() {
        return new CardAggregated2();
    }

    /**
     * Create an instance of {@link InterestType1Choice }
     * 
     */
    public InterestType1Choice createInterestType1Choice() {
        return new InterestType1Choice();
    }

    /**
     * Create an instance of {@link DateAndType1 }
     * 
     */
    public DateAndType1 createDateAndType1() {
        return new DateAndType1();
    }

    /**
     * Create an instance of {@link ImpliedCurrencyAmountRange1Choice }
     * 
     */
    public ImpliedCurrencyAmountRange1Choice createImpliedCurrencyAmountRange1Choice() {
        return new ImpliedCurrencyAmountRange1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType3 }
     * 
     */
    public CreditorReferenceType3 createCreditorReferenceType3() {
        return new CreditorReferenceType3();
    }

    /**
     * Create an instance of {@link GarnishmentType1Choice }
     * 
     */
    public GarnishmentType1Choice createGarnishmentType1Choice() {
        return new GarnishmentType1Choice();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd13DecimalAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAnd13DecimalAmount createActiveOrHistoricCurrencyAnd13DecimalAmount() {
        return new ActiveOrHistoricCurrencyAnd13DecimalAmount();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification8 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification8 createBranchAndFinancialInstitutionIdentification8() {
        return new BranchAndFinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link PointOfInteraction1 }
     * 
     */
    public PointOfInteraction1 createPointOfInteraction1() {
        return new PointOfInteraction1();
    }

    /**
     * Create an instance of {@link RemittanceInformation22 }
     * 
     */
    public RemittanceInformation22 createRemittanceInformation22() {
        return new RemittanceInformation22();
    }

    /**
     * Create an instance of {@link PaymentCard4 }
     * 
     */
    public PaymentCard4 createPaymentCard4() {
        return new PaymentCard4();
    }

    /**
     * Create an instance of {@link EntryDetails14 }
     * 
     */
    public EntryDetails14 createEntryDetails14() {
        return new EntryDetails14();
    }

    /**
     * Create an instance of {@link BalanceType13 }
     * 
     */
    public BalanceType13 createBalanceType13() {
        return new BalanceType13();
    }

    /**
     * Create an instance of {@link TransactionPrice4Choice }
     * 
     */
    public TransactionPrice4Choice createTransactionPrice4Choice() {
        return new TransactionPrice4Choice();
    }

    /**
     * Create an instance of {@link BalanceType10Choice }
     * 
     */
    public BalanceType10Choice createBalanceType10Choice() {
        return new BalanceType10Choice();
    }

    /**
     * Create an instance of {@link DocumentLineType1 }
     * 
     */
    public DocumentLineType1 createDocumentLineType1() {
        return new DocumentLineType1();
    }

    /**
     * Create an instance of {@link PartyIdentification272 }
     * 
     */
    public PartyIdentification272 createPartyIdentification272() {
        return new PartyIdentification272();
    }

    /**
     * Create an instance of {@link CardIndividualTransaction2 }
     * 
     */
    public CardIndividualTransaction2 createCardIndividualTransaction2() {
        return new CardIndividualTransaction2();
    }

    /**
     * Create an instance of {@link OtherContact1 }
     * 
     */
    public OtherContact1 createOtherContact1() {
        return new OtherContact1();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CorporateAction82 }
     * 
     */
    public CorporateAction82 createCorporateAction82() {
        return new CorporateAction82();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation8 }
     * 
     */
    public ReferredDocumentInformation8 createReferredDocumentInformation8() {
        return new ReferredDocumentInformation8();
    }

    /**
     * Create an instance of {@link BatchInformation2 }
     * 
     */
    public BatchInformation2 createBatchInformation2() {
        return new BatchInformation2();
    }

    /**
     * Create an instance of {@link Pagination1 }
     * 
     */
    public Pagination1 createPagination1() {
        return new Pagination1();
    }

    /**
     * Create an instance of {@link TaxAmount3 }
     * 
     */
    public TaxAmount3 createTaxAmount3() {
        return new TaxAmount3();
    }

    /**
     * Create an instance of {@link GroupHeader116 }
     * 
     */
    public GroupHeader116 createGroupHeader116() {
        return new GroupHeader116();
    }

    /**
     * Create an instance of {@link TransactionDates3 }
     * 
     */
    public TransactionDates3 createTransactionDates3() {
        return new TransactionDates3();
    }

    /**
     * Create an instance of {@link SequenceRange1 }
     * 
     */
    public SequenceRange1 createSequenceRange1() {
        return new SequenceRange1();
    }

    /**
     * Create an instance of {@link CorporateActionEventType104Choice }
     * 
     */
    public CorporateActionEventType104Choice createCorporateActionEventType104Choice() {
        return new CorporateActionEventType104Choice();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure6 }
     * 
     */
    public BankTransactionCodeStructure6 createBankTransactionCodeStructure6() {
        return new BankTransactionCodeStructure6();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure4 }
     * 
     */
    public BankTransactionCodeStructure4 createBankTransactionCodeStructure4() {
        return new BankTransactionCodeStructure4();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure5 }
     * 
     */
    public BankTransactionCodeStructure5 createBankTransactionCodeStructure5() {
        return new BankTransactionCodeStructure5();
    }

    /**
     * Create an instance of {@link AmountRangeBoundary1 }
     * 
     */
    public AmountRangeBoundary1 createAmountRangeBoundary1() {
        return new AmountRangeBoundary1();
    }

    /**
     * Create an instance of {@link TaxRecord3 }
     * 
     */
    public TaxRecord3 createTaxRecord3() {
        return new TaxRecord3();
    }

    /**
     * Create an instance of {@link CreditLineType1Choice }
     * 
     */
    public CreditLineType1Choice createCreditLineType1Choice() {
        return new CreditLineType1Choice();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link YieldedOrValueType1Choice }
     * 
     */
    public YieldedOrValueType1Choice createYieldedOrValueType1Choice() {
        return new YieldedOrValueType1Choice();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link DocumentLineType1Choice }
     * 
     */
    public DocumentLineType1Choice createDocumentLineType1Choice() {
        return new DocumentLineType1Choice();
    }

    /**
     * Create an instance of {@link IdentificationSource3Choice }
     * 
     */
    public IdentificationSource3Choice createIdentificationSource3Choice() {
        return new IdentificationSource3Choice();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link TransactionAllocation1 }
     * 
     */
    public TransactionAllocation1 createTransactionAllocation1() {
        return new TransactionAllocation1();
    }

    /**
     * Create an instance of {@link OrganisationIdentification39 }
     * 
     */
    public OrganisationIdentification39 createOrganisationIdentification39() {
        return new OrganisationIdentification39();
    }

    /**
     * Create an instance of {@link TransactionReferences6 }
     * 
     */
    public TransactionReferences6 createTransactionReferences6() {
        return new TransactionReferences6();
    }

    /**
     * Create an instance of {@link CashDeposit1 }
     * 
     */
    public CashDeposit1 createCashDeposit1() {
        return new CashDeposit1();
    }

    /**
     * Create an instance of {@link PostalAddress27 }
     * 
     */
    public PostalAddress27 createPostalAddress27() {
        return new PostalAddress27();
    }

    /**
     * Create an instance of {@link TransactionParties12 }
     * 
     */
    public TransactionParties12 createTransactionParties12() {
        return new TransactionParties12();
    }

    /**
     * Create an instance of {@link Contact13 }
     * 
     */
    public Contact13 createContact13() {
        return new Contact13();
    }

    /**
     * Create an instance of {@link DatePeriod2 }
     * 
     */
    public DatePeriod2 createDatePeriod2() {
        return new DatePeriod2();
    }

    /**
     * Create an instance of {@link Price7 }
     * 
     */
    public Price7 createPrice7() {
        return new Price7();
    }

    /**
     * Create an instance of {@link TaxAuthorisation1 }
     * 
     */
    public TaxAuthorisation1 createTaxAuthorisation1() {
        return new TaxAuthorisation1();
    }

    /**
     * Create an instance of {@link ReturnReason5Choice }
     * 
     */
    public ReturnReason5Choice createReturnReason5Choice() {
        return new ReturnReason5Choice();
    }

    /**
     * Create an instance of {@link CardSecurityInformation1 }
     * 
     */
    public CardSecurityInformation1 createCardSecurityInformation1() {
        return new CardSecurityInformation1();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions1 }
     * 
     */
    public NumberAndSumOfTransactions1 createNumberAndSumOfTransactions1() {
        return new NumberAndSumOfTransactions1();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions4 }
     * 
     */
    public NumberAndSumOfTransactions4 createNumberAndSumOfTransactions4() {
        return new NumberAndSumOfTransactions4();
    }

    /**
     * Create an instance of {@link TaxPeriod3 }
     * 
     */
    public TaxPeriod3 createTaxPeriod3() {
        return new TaxPeriod3();
    }

    /**
     * Create an instance of {@link CashAccount43 }
     * 
     */
    public CashAccount43 createCashAccount43() {
        return new CashAccount43();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link CurrencyExchange24 }
     * 
     */
    public CurrencyExchange24 createCurrencyExchange24() {
        return new CurrencyExchange24();
    }

    /**
     * Create an instance of {@link AccountStatement14 }
     * 
     */
    public AccountStatement14 createAccountStatement14() {
        return new AccountStatement14();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity33Choice }
     * 
     */
    public FinancialInstrumentQuantity33Choice createFinancialInstrumentQuantity33Choice() {
        return new FinancialInstrumentQuantity33Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link ProprietaryQuantity1 }
     * 
     */
    public ProprietaryQuantity1 createProprietaryQuantity1() {
        return new ProprietaryQuantity1();
    }

    /**
     * Create an instance of {@link CashAccount40 }
     * 
     */
    public CashAccount40 createCashAccount40() {
        return new CashAccount40();
    }

    /**
     * Create an instance of {@link ProprietaryBankTransactionCodeStructure1 }
     * 
     */
    public ProprietaryBankTransactionCodeStructure1 createProprietaryBankTransactionCodeStructure1() {
        return new ProprietaryBankTransactionCodeStructure1();
    }

    /**
     * Create an instance of {@link PointOfInteractionCapabilities1 }
     * 
     */
    public PointOfInteractionCapabilities1 createPointOfInteractionCapabilities1() {
        return new PointOfInteractionCapabilities1();
    }

    /**
     * Create an instance of {@link Party52Choice }
     * 
     */
    public Party52Choice createParty52Choice() {
        return new Party52Choice();
    }

    /**
     * Create an instance of {@link Garnishment4 }
     * 
     */
    public Garnishment4 createGarnishment4() {
        return new Garnishment4();
    }

    /**
     * Create an instance of {@link OriginalAndCurrentQuantities1 }
     * 
     */
    public OriginalAndCurrentQuantities1 createOriginalAndCurrentQuantities1() {
        return new OriginalAndCurrentQuantities1();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmountRange2 }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmountRange2 createActiveOrHistoricCurrencyAndAmountRange2() {
        return new ActiveOrHistoricCurrencyAndAmountRange2();
    }

    /**
     * Create an instance of {@link DateTimePeriod1 }
     * 
     */
    public DateTimePeriod1 createDateTimePeriod1() {
        return new DateTimePeriod1();
    }

    /**
     * Create an instance of {@link PaymentReturnReason8 }
     * 
     */
    public PaymentReturnReason8 createPaymentReturnReason8() {
        return new PaymentReturnReason8();
    }

    /**
     * Create an instance of {@link BankToCustomerStatementV13 }
     * 
     */
    public BankToCustomerStatementV13 createBankToCustomerStatementV13() {
        return new BankToCustomerStatementV13();
    }

    /**
     * Create an instance of {@link ProprietaryDate3 }
     * 
     */
    public ProprietaryDate3 createProprietaryDate3() {
        return new ProprietaryDate3();
    }

    /**
     * Create an instance of {@link RateType4Choice }
     * 
     */
    public RateType4Choice createRateType4Choice() {
        return new RateType4Choice();
    }

    /**
     * Create an instance of {@link TransactionQuantities4Choice }
     * 
     */
    public TransactionQuantities4Choice createTransactionQuantities4Choice() {
        return new TransactionQuantities4Choice();
    }

    /**
     * Create an instance of {@link TotalTransactions6 }
     * 
     */
    public TotalTransactions6 createTotalTransactions6() {
        return new TotalTransactions6();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ProprietaryReference1 }
     * 
     */
    public ProprietaryReference1 createProprietaryReference1() {
        return new ProprietaryReference1();
    }

    /**
     * Create an instance of {@link NameAndAddress18 }
     * 
     */
    public NameAndAddress18 createNameAndAddress18() {
        return new NameAndAddress18();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link AddressType3Choice }
     * 
     */
    public AddressType3Choice createAddressType3Choice() {
        return new AddressType3Choice();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation18 }
     * 
     */
    public StructuredRemittanceInformation18 createStructuredRemittanceInformation18() {
        return new StructuredRemittanceInformation18();
    }

    /**
     * Create an instance of {@link TransactionInterest4 }
     * 
     */
    public TransactionInterest4 createTransactionInterest4() {
        return new TransactionInterest4();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link MessageIdentification2 }
     * 
     */
    public MessageIdentification2 createMessageIdentification2() {
        return new MessageIdentification2();
    }

    /**
     * Create an instance of {@link Party50Choice }
     * 
     */
    public Party50Choice createParty50Choice() {
        return new Party50Choice();
    }

    /**
     * Create an instance of {@link TechnicalInputChannel1Choice }
     * 
     */
    public TechnicalInputChannel1Choice createTechnicalInputChannel1Choice() {
        return new TechnicalInputChannel1Choice();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice }
     * 
     */
    public ProxyAccountType1Choice createProxyAccountType1Choice() {
        return new ProxyAccountType1Choice();
    }

    /**
     * Create an instance of {@link RemittanceLocationData2 }
     * 
     */
    public RemittanceLocationData2 createRemittanceLocationData2() {
        return new RemittanceLocationData2();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link TaxData1 }
     * 
     */
    public TaxData1 createTaxData1() {
        return new TaxData1();
    }

    /**
     * Create an instance of {@link TrackData1 }
     * 
     */
    public TrackData1 createTrackData1() {
        return new TrackData1();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation27 }
     * 
     */
    public PaymentTypeInformation27 createPaymentTypeInformation27() {
        return new PaymentTypeInformation27();
    }

    /**
     * Create an instance of {@link DocumentAmountType1Choice }
     * 
     */
    public DocumentAmountType1Choice createDocumentAmountType1Choice() {
        return new DocumentAmountType1Choice();
    }

    /**
     * Create an instance of {@link Product2 }
     * 
     */
    public Product2 createProduct2() {
        return new Product2();
    }

    /**
     * Create an instance of {@link References74Choice }
     * 
     */
    public References74Choice createReferences74Choice() {
        return new References74Choice();
    }

    /**
     * Create an instance of {@link EntryStatus1Choice }
     * 
     */
    public EntryStatus1Choice createEntryStatus1Choice() {
        return new EntryStatus1Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification32 }
     * 
     */
    public GenericIdentification32 createGenericIdentification32() {
        return new GenericIdentification32();
    }

    /**
     * Create an instance of {@link OtherIdentification1 }
     * 
     */
    public OtherIdentification1 createOtherIdentification1() {
        return new OtherIdentification1();
    }

    /**
     * Create an instance of {@link CashAvailability1 }
     * 
     */
    public CashAvailability1 createCashAvailability1() {
        return new CashAvailability1();
    }

    /**
     * Create an instance of {@link GenericIdentification30 }
     * 
     */
    public GenericIdentification30 createGenericIdentification30() {
        return new GenericIdentification30();
    }

    /**
     * Create an instance of {@link PointOfInteractionComponent1 }
     * 
     */
    public PointOfInteractionComponent1 createPointOfInteractionComponent1() {
        return new PointOfInteractionComponent1();
    }

    /**
     * Create an instance of {@link CardTransaction18 }
     * 
     */
    public CardTransaction18 createCardTransaction18() {
        return new CardTransaction18();
    }

    /**
     * Create an instance of {@link PersonIdentification18 }
     * 
     */
    public PersonIdentification18 createPersonIdentification18() {
        return new PersonIdentification18();
    }

    /**
     * Create an instance of {@link TransactionIdentifier1 }
     * 
     */
    public TransactionIdentifier1 createTransactionIdentifier1() {
        return new TransactionIdentifier1();
    }

    /**
     * Create an instance of {@link CashBalance8 }
     * 
     */
    public CashBalance8 createCashBalance8() {
        return new CashBalance8();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CreditLine3 }
     * 
     */
    public CreditLine3 createCreditLine3() {
        return new CreditLine3();
    }

    /**
     * Create an instance of {@link SecuritiesAccount19 }
     * 
     */
    public SecuritiesAccount19 createSecuritiesAccount19() {
        return new SecuritiesAccount19();
    }

    /**
     * Create an instance of {@link ProprietaryPrice2 }
     * 
     */
    public ProprietaryPrice2 createProprietaryPrice2() {
        return new ProprietaryPrice2();
    }

    /**
     * Create an instance of {@link PaymentContext3 }
     * 
     */
    public PaymentContext3 createPaymentContext3() {
        return new PaymentContext3();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link TransactionAgents6 }
     * 
     */
    public TransactionAgents6 createTransactionAgents6() {
        return new TransactionAgents6();
    }

    /**
     * Create an instance of {@link DocumentLineIdentification1 }
     * 
     */
    public DocumentLineIdentification1 createDocumentLineIdentification1() {
        return new DocumentLineIdentification1();
    }

    /**
     * Create an instance of {@link FromToAmountRange1 }
     * 
     */
    public FromToAmountRange1 createFromToAmountRange1() {
        return new FromToAmountRange1();
    }

    /**
     * Create an instance of {@link Charges15 }
     * 
     */
    public Charges15 createCharges15() {
        return new Charges15();
    }

    /**
     * Create an instance of {@link CashAvailabilityDate1Choice }
     * 
     */
    public CashAvailabilityDate1Choice createCashAvailabilityDate1Choice() {
        return new CashAvailabilityDate1Choice();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link Rate4 }
     * 
     */
    public Rate4 createRate4() {
        return new Rate4();
    }

    /**
     * Create an instance of {@link CardTransaction3Choice }
     * 
     */
    public CardTransaction3Choice createCardTransaction3Choice() {
        return new CardTransaction3Choice();
    }

    /**
     * Create an instance of {@link ProprietaryParty6 }
     * 
     */
    public ProprietaryParty6 createProprietaryParty6() {
        return new ProprietaryParty6();
    }

    /**
     * Create an instance of {@link SecurityIdentification19 }
     * 
     */
    public SecurityIdentification19 createSecurityIdentification19() {
        return new SecurityIdentification19();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link CardSequenceNumberRange1 }
     * 
     */
    public CardSequenceNumberRange1 createCardSequenceNumberRange1() {
        return new CardSequenceNumberRange1();
    }

    /**
     * Create an instance of {@link DisplayCapabilities1 }
     * 
     */
    public DisplayCapabilities1 createDisplayCapabilities1() {
        return new DisplayCapabilities1();
    }

    /**
     * Create an instance of {@link PlainCardData1 }
     * 
     */
    public PlainCardData1 createPlainCardData1() {
        return new PlainCardData1();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2Choice }
     * 
     */
    public CreditorReferenceType2Choice createCreditorReferenceType2Choice() {
        return new CreditorReferenceType2Choice();
    }

    /**
     * Create an instance of {@link CardholderAuthentication2 }
     * 
     */
    public CardholderAuthentication2 createCardholderAuthentication2() {
        return new CardholderAuthentication2();
    }

    /**
     * Create an instance of {@link AmountAndDirection35 }
     * 
     */
    public AmountAndDirection35 createAmountAndDirection35() {
        return new AmountAndDirection35();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link TaxParty1 }
     * 
     */
    public TaxParty1 createTaxParty1() {
        return new TaxParty1();
    }

    /**
     * Create an instance of {@link RemittanceLocation8 }
     * 
     */
    public RemittanceLocation8 createRemittanceLocation8() {
        return new RemittanceLocation8();
    }

    /**
     * Create an instance of {@link TaxParty2 }
     * 
     */
    public TaxParty2 createTaxParty2() {
        return new TaxParty2();
    }

    /**
     * Create an instance of {@link GarnishmentType1 }
     * 
     */
    public GarnishmentType1 createGarnishmentType1() {
        return new GarnishmentType1();
    }

    /**
     * Create an instance of {@link BalanceSubType1Choice }
     * 
     */
    public BalanceSubType1Choice createBalanceSubType1Choice() {
        return new BalanceSubType1Choice();
    }

    /**
     * Create an instance of {@link RemittanceAmount4 }
     * 
     */
    public RemittanceAmount4 createRemittanceAmount4() {
        return new RemittanceAmount4();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification2 }
     * 
     */
    public GenericPersonIdentification2 createGenericPersonIdentification2() {
        return new GenericPersonIdentification2();
    }

    /**
     * Create an instance of {@link DateOrDateTimePeriod1Choice }
     * 
     */
    public DateOrDateTimePeriod1Choice createDateOrDateTimePeriod1Choice() {
        return new DateOrDateTimePeriod1Choice();
    }

    /**
     * Create an instance of {@link DateType2Choice }
     * 
     */
    public DateType2Choice createDateType2Choice() {
        return new DateType2Choice();
    }

    /**
     * Create an instance of {@link ReportingSource1Choice }
     * 
     */
    public ReportingSource1Choice createReportingSource1Choice() {
        return new ReportingSource1Choice();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link ChargeType3Choice }
     * 
     */
    public ChargeType3Choice createChargeType3Choice() {
        return new ChargeType3Choice();
    }

    /**
     * Create an instance of {@link DocumentType2Choice }
     * 
     */
    public DocumentType2Choice createDocumentType2Choice() {
        return new DocumentType2Choice();
    }

    /**
     * Create an instance of {@link BranchData5 }
     * 
     */
    public BranchData5 createBranchData5() {
        return new BranchData5();
    }

    /**
     * Create an instance of {@link ReportEntry15 }
     * 
     */
    public ReportEntry15 createReportEntry15() {
        return new ReportEntry15();
    }

    /**
     * Create an instance of {@link ProprietaryAgent5 }
     * 
     */
    public ProprietaryAgent5 createProprietaryAgent5() {
        return new ProprietaryAgent5();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation3 }
     * 
     */
    public CreditorReferenceInformation3 createCreditorReferenceInformation3() {
        return new CreditorReferenceInformation3();
    }

    /**
     * Create an instance of {@link InterestRecord2 }
     * 
     */
    public InterestRecord2 createInterestRecord2() {
        return new InterestRecord2();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails5 }
     * 
     */
    public AmountAndCurrencyExchangeDetails5 createAmountAndCurrencyExchangeDetails5() {
        return new AmountAndCurrencyExchangeDetails5();
    }

    /**
     * Create an instance of {@link DocumentAmount1 }
     * 
     */
    public DocumentAmount1 createDocumentAmount1() {
        return new DocumentAmount1();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails6 }
     * 
     */
    public AmountAndCurrencyExchangeDetails6 createAmountAndCurrencyExchangeDetails6() {
        return new AmountAndCurrencyExchangeDetails6();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.053.001.13", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
